version: '3.9'
services:
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: db
    ports:
      - 3002:3306
    restart: 'always'
    volumes:
      - mysqldata:/data/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

volumes:
  mysqldata:
    driver: local